# This is a basic workflow to help you get started with Actions

name: Build & Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - master
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  MAPBOX_KEY: secrets.MAPBOX_KEY
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linter:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: ScaCap/action-ktlint@master
      with:
        android: true
        github_token: ${{ secrets.GTHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: true
        level: error

  build_unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Run Build
        run: ./gradlew clean build -x testDebugUnitTest -x testReleaseUnitTest
      - name: Run Test
        run: |
          ./gradlew test
          ./gradlew koverMergedXmlReport
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_KEY }} 
