name: Instrumented tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - master
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
  
jobs:
  instrumented_test:
    runs-on: macos-latest
    timeout-minutes: 45
    strategy:
      matrix:
        api-level: [28, 29, 30]
        target: [google_apis]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.4.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: ./gradlew testDebugUnitTest
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_KEY }}
          files: "app/build/reports/coverage/debug/report.xml"
