name: Checking coverage
on: 
 pull_request:
    types: [opened]
    branches: 
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3.2.0
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: gradle
    - name: Check coverage metrics
      run: ./gradlew check

    - uses: codecov/codecov-action@v2
      with:
       token: ${{ secrets.CODECOV_KEY }}
